# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 6 * * 1" # will run every Monday at 6 am
    - cron: "32 11 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Scheduled Deployment
    if: github.repository == 'opxop/bookshelf'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # maybe do something eles first
      
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      
